FROM ubuntu:latest

RUN apt-get -y update
RUN apt-get -y install wget
RUN apt-get -y install software-properties-common
RUN rm -rf /var/lib/apt/lists/*

# Adding repositories    
RUN apt-add-repository 'deb http://archive.ubuntu.com/ubuntu focal multiverse'
RUN apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
#RUN apt-add-repository ppa:repository/ppa
RUN add-apt-repository ppa:mozillateam/ppa
RUN apt-get -y update

# Install libxmu6
RUN apt-get -y install libxmu6

# Install libglu1-mesa
RUN apt-get -y install libglu1-mesa

#Install Firefox
RUN apt-get -y install dbus-x11
RUN apt-get -y install fonts-freefont-ttf
RUN apt-get -y install firefox-esr
RUN apt-get -y install libcanberra-gtk-module
#RUN apt-get -y install libcanberra-gtk2
RUN apt-get -y install pulseaudio

RUN mkdir /home/user
RUN adduser user --home /home/user
RUN chown -R user:root /home/user
RUN chmod 770 /home/user
RUN ls -la /home

WORKDIR /home/user
USER user

ENTRYPOINT ["/usr/bin/firefox-esr", "--no-remote"]

#docker image rm ubuntu/firefox; docker build -t ubuntu/firefox -f Dockerfile-Ubuntu_Firefox .
#docker run --rm -it -e DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix -v /dev/snd:/dev/snd --privileged ubuntu/firefox